### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by scottbedard** [scottbedard/speedcube.site#110]
Since the 3.x branch is has started getting more stable, it's time to start looking at how to get the new site to the finish line. This ticket will outline the various things that need to happen to ensure a smooth launch. New issues will be created for these points as they start being worked on.

> **Note:** For anyone interested in playing with the new site or puzzles, be aware that things are very unstable and changing all the time. Additionally, databases are reset on every deployment so nothing will be saved.

### Important components

- [x] [3D components](http://next.speedcube.site/sandbox)
- [x] [`<v-button>`](http://next.speedcube.site/components?filter=button)
- [x] [`<v-card>`](http://next.speedcube.site/components?filter=card)
- [ ] `<v-color-picker>`
- [x] [`<v-cube>`](http://next.speedcube.site/components?filter=cube)
- [x] [`<v-dodecaminx>`](http://next.speedcube.site/components?filter=dodecaminx)
- [ ] `<v-modal>`
- [x] [`<v-range-input>`](http://next.speedcube.site/components?filter=range-input)

### Features

- [ ] Home page
- [ ] Forgot password page
- [x] [Login page](http://next.speedcube.site/login)
- [ ] Personal stats page
- [ ] Records page
- [ ] Replay page
- [x] [Signup page](http://next.speedcube.site/signup)
- [ ] Solve page
  - [ ] Appearance editors
  - [ ] Keybinding editors
- [ ] Standings page
- [ ] Terms of service page

### Ops

- [ ] Create staging server with mock data
- [ ] Setup production deployments
- [ ] Migrate databases
- [ ] Configure email service
- [ ] Automated database backups

### General todos

- [ ] Release a 1.x version of Twister
