### ISSUE TITLE
Appearance editors

### ISSUE THREAD

**Issue by scottbedard** [scottbedard/speedcube.site#111]
Puzzle appearances are going to work slightly differently in 3.x. Previously, each `Solve` model had it's own `config` property. While this works fine, it's not very space efficient. Users hardly ever change their configurations once they start solving, so there is no need to duplicate it over and over again in storage.

For 3.x, we'll create a new `Config` model, which will be connected to the `Solve` model via a one-to-one relationship. When configuration changes, we'll create a new `Config`. Once a config has been used for a solve, it will be considered locked, and any new changes must create a new model. Along with this being more efficient, it will also open up the possibility of users sharing configurations with one another down the road.

### Tasks

- [x] Create `<v-color-picker>` component
- [x] Create `Config` model
- [x] Create API endpoints
- [x] Build frontend editor
